# Generated by Django 3.2 on 2021-04-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, unique=True)),
                ('user_pw', models.TextField()),
                ('user_name', models.CharField(max_length=30)),
                ('user_validation', models.CharField(default='0', max_length=5)),
            ],
        ),
    ]
